name: Release
on:
  workflow_dispatch:
  repository_dispatch:
    types: [infracost_choco]

jobs:
  build:
    name: Release Infracost choco
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate & push
        run: infracost/build.ps1
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
